### ISSUE TITLE
Use --verbose and --colour options appropriately

### ISSUE THREAD

**Issue by robert-kisteleki** [RIPE-NCC/ripe-atlas-tools#103]
At the moment there's an amount of extra text besides the output. This should only appear if the user actually asks for it

**Comment by danielquinn** [comment]
Until now I've avoided use of a `--colour` flag by making sure that all use of colour is wrapped in a check for `is_tty()`.  That way piping the output through a program won't inadvertently dump the formatting data as well.  I've considered a global `--no-colour` flag though, but that's actually kind of a pain in the ass so I've not prioritised it.  The easiest way to implement this would be to have the user set it in their config rather than handling `--no-colour` for every command.

As for --verbose, I think this is more of a personal call: what constitutes part of the standard output and what doesn't?  Typically, verbosity isn't about the format of the output so much as the debugging/logging of what's going on behind the scenes.  The use of the header in reports for example: that's not really a question of verbosity as much as user preference.  We're building a user interface here, not just a input/output tool, so some of this stuff should be considered standard.

Take `ls` or `ps` for example.  Both include a header line that's just expected to be part of the output.  More elaborate tools like `git` and Gentoo's `equery` or `portage` also have formatting around the tabular data that just makes sense in that context.  I'd hate to remove text that's basically formatting for human readability by default.

However, if you'd like to add something like a `--no-header`, `--no-footer` or even `--data-only` or something, that can probably be arranged with little effort.

**Comment by robert-kisteleki** [comment]
I believe the default should be minimal, to-the-point output. The intention for the tool is to mimic standard tools such as ping and traceroute -- both of them only have minimal meta information (a single header line) beyond the actual results. This makes it easier to pipe the output through other programs and process it further.

So, perhaps a header line such as "msm 1234567 created with X probes" plus the results is good enough (that is, for msm creation)

**Comment by danielquinn** [comment]
So specifically, you're suggesting that the `report` command have a limited header, correct?  So this:

```
$ ripe-atlas report 1000005

RIPE Atlas Report for Measurement #1234567
===================================================
Measurement description here

Probe #197

  1 192.168.1.1                                1.843 ms     2.279 ms     1.959 ms
  ...
```

would become this:

```
$ ripe-atlas report 1000005
Measurement 1234567: Measurement description here (or # of probes, whatever)
Probe #197

  1 192.168.1.1                                1.843 ms     2.279 ms     1.959 ms
  ...
```

...or even this?

```
$ ripe-atlas report 1000005
Probe #197

  1 192.168.1.1                                1.843 ms     2.279 ms     1.959 ms
  ...
```

Given the choice, I think I'd opt for the second one, but I'd also introduce something like the equivalent to the measurements detail page on the site, as we don't currently have something for that.  Something like:

```
$ ripe-atlas measurement 1234567
#1234567: My measurement description
Type: Traceroute
Started: 2015-01-01
Stopped: 2015-06-01
...
```

...because I think that that's what I was trying to achieve with that sort of header.  I agree though, it's basically superfluous for the job at hand.  A more detailed measurement metadata command would be useful though.  What say you?

**Comment by danielquinn** [comment]
I just realised that while there's a merged PR associated with this ticket, I still haven't removed the excess headers, so I'll reopen and do that first.
