### ISSUE TITLE
Use a specific user agent string for queries made by Magellan

### ISSUE THREAD

**Issue by robert-kisteleki** [RIPE-NCC/ripe-atlas-tools#122]
It'd be highly useful for the Atlas core team to know how much this tool is used Using the UA (tool, version) to let the service know would go a long way. This should apply to all interactions with the API (measurements, probes, streaming).

For bonus points: as a byproduct, package maintainers could have a simple way to set this for themselves.

**Comment by astrikos** [comment]
That would need support for Cousteau. It currently sets the header to "RIPE ATLAS Cousteau v{0}", so everything get this header. You've discussed before with @danielquinn, but we left it there since it would need support for both packages. I guess since more people find it useful we could schedule it.
For maintainer I guess we could have a empty file in the repo that we read from, and the maintainer can change it at will.

**Comment by danielquinn** [comment]
@astrikos this was roughly my thinking, though I was just going to have the user-agent in the config.  If Cousteau can be tweaked to have `user_agent=` in the __init__ with a default of `RIPE ATLAS Cousteau v{0}"` if nothing is defined, then we can easily set this in `commands.measure.base.run()` with a value coming from a config value.

**Comment by astrikos** [comment]
I think from a maintainers point of view it would be easier to do something like: 
```code
echo "RIPE Atlas Tools v1.1 for OpenBSD" > ripe/atlas/tools/http_agent
```
than writing yaml file (could a syntax error somewhere in the yaml file leads to inability of parsing whole file? not sure but if yes we should avoid having the risk to break whole package)
For cousteau yes that would be the way, I agree.

**Comment by danielquinn** [comment]
Ah I see what you mean.  Yes that makes sense.  I'm on board.

**Comment by danielquinn** [comment]
I'm starting on RIPE-NCC/ripe-atlas-cousteau#15 as part of this ticket now.
