### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by danielquinn** [RIPE-NCC/ripe-atlas-tools#158]
We've got a sexy command line client here.  We should show it off in the README.  I believe Vesna should have some of the screenshots I took a while back.

This issue was inspired by a [recent Reddit post on the subject](https://www.reddit.com/r/linux/comments/4bca77/visual_blindness_of_linux_programmers/).

**Comment by hellerve** [comment]
I'll just leave my two cents here, because I care about showing off good projects: I find [asciinema](https://asciinema.org/) to be very appealling. Not only does it provide the user with an interactive tutorial, but you can also copy and paste things you see in the cinema, which is pretty neat. A downside of this is of course that it's a link to another site and you only get to see the static picture in the README itself, but oh well.

**Comment by chrisamin** [comment]
Screenshots added in aae6772d6413457f570027b033a15fc8b251d036
