### ISSUE TITLE
Exposing measurement metadata to renderers

### ISSUE THREAD

**Issue by ioc32** [RIPE-NCC/ripe-atlas-tools#23]
If on_start() and on_finish() in the base renderer exposed measurement metadata directly, the reports could include relevant metadata about the results the report is displaying, making it all more useful.

Is this in the "roadmap"? If it is not, would anybody else like to see it in?

**Comment by astrikos** [comment]
I think it's a good idea. Now that I am thinking of it we could maybe have a renderer for probes & measurements. First could be used from probe search command and second in your case and in the measurement search command (if we ever have any).
In your case I would do it optional though and enable it with an arg, since it's an additional call and not everyone could be interested. I could probably do the probe renderer since I started with the probe search unless someone else wants to take on both.

**Comment by chrisamin** [comment]
on_start and on_finish were replaced with on_result long ago
