### ISSUE TITLE
yaml dependency unclear

### ISSUE THREAD

**Issue by bortzmeyer** [RIPE-NCC/ripe-atlas-tools#3]
If libyaml devlopment files are not installed, it is apparently not done automatically by pip install:

  Running setup.py install for pyyaml
    checking if libyaml is compilable
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/check_libyaml.c -o build/temp.linux-x86_64-2.7/check_libyaml.o
    build/temp.linux-x86_64-2.7/check_libyaml.c:2:18: fatal error: yaml.h: No such file or directory
    compilation terminated.
    
    libyaml is not found or a compiler error: forcing --without-libyaml
    (if libyaml is installed correctly, you may need to
     specify the option --include-dirs or uncomment and
     modify the parameter include_dirs in setup.cfg)

**Comment by danielquinn** [comment]
What environment are you seeing this kind of thing in?  I've got a bunch of Vagrant boxes here, so I can spin up a few flavours of Debian, Ubuntu, Fedora, CentOS, or Gentoo if need be.

**Comment by bortzmeyer** [comment]
Debian stable "jessie"

**Comment by danielquinn** [comment]
Alright, I've spent much of today trying out installations in different distributions: Debian/Jessie, Debian/Weezy, CentOS7, and Gentoo.  I've added documentation to the `README` to help with the process, but from what I can tell, this isn't actually a problem.

If libyaml is available, it'll use that, otherwise it'll use a (slower) pure-python option.  Given that this is only ever used for the configuration system, I don't think this is a problem.

If you're actually getting errors while trying to use the `ripe-atlas` program, then I'll worry, but if it's just the installer complaining, I don't think this should be something we concern ourselves with.
