### ISSUE TITLE
Support for abbreviated commands 

### ISSUE THREAD

**Issue by cod3monk** [RIPE-NCC/ripe-atlas-tools#54]
Instead of `ripe-atlas measure ping ...`, `ripe-atlas m p ...` would be faster to use and unambiguous as well.

Here is a code snippet which adds that functionality to `argparse`: http://guido.vonrudorff.de/python-argparse-graceful-parameter-parsing/

**Comment by danielquinn** [comment]
We've already got some code in there to allow for aliasing in how the command is called, which may solve this for you, though this isn't fully implemented yet.

The idea is that on installation, a single script, `ripe-atlas` will be installed, along with a bunch of symlinks: `rping`, `rtraceroute`, `rdig`, etc.  Calling `rping` will have the same effect as calling `ripe-atlas measure ping`.

Beyond that you're free to create your own aliases to make things easy for you.

The reason I'm resistant to this is three-fold:

* Abbreviated arguments is really uncommon in the wild, so this would be a break with established norms.
* Verbosity is helpful for people learning the tools, so if how-to's start popping up with abbreviated commands, we're introducing an unnecessary learning curve.
* This isn't future-proof.  As Magellan (this toolkit) is still a work in progress, it's entirely likely that we'll introduce another command that starts with the same letter(s).  Indeed, we already have.  Your example wouldn't work because we just introduced a `measurements` command, which shares the entirety of letters in the `measure` command.

My recommendation for you would be to go the typical route of simply creating aliases for your personally commonly-used tasks.  When we get the aforementioned abbreviated scripts installed though, that might make things easy out-of-the-box too.

**Comment by danielquinn** [comment]
Strike that, the symlink trick mentioned above was 95% working.  I just committed the last bit and it appears to be functional now.  So now you can:

    $ aping --target example.com

and it has the same effect as:

    $ ripe-atlas measure ping --target example.com

I'm going to leave this issue open over the weekend in case you or anyone else wants to add comments, but given the points I outlined above, I don't think we'll be supporting abbreviated arguments -- at least not until the commands are more stable.

**Comment by danielquinn** [comment]
As it's Monday end-of-day, I'm going to close this now.  Maybe in a few months, when we've got a more stable codebase, we can revisit this one.
