### ISSUE TITLE
API key fetch

### ISSUE THREAD

**Issue by astrikos** [RIPE-NCC/ripe-atlas-tools#99]
Someone from hackathon suggested we have a programmatic way to fetch key from a config place.
Something like:

``` python
from ripe.atlas import key_mng
ckey = key_mng.get_create_key()
rkey = key_mng.get_results_key()
```

I am not sure if the place of implementation is here, cause I see people using cousteau can use that as well. So, maybe we should implemented in cousteau and then use it here??
We could use a similar path structure $HOME/.config/ripe-atlas

**Comment by danielquinn** [comment]
I agree that this is probably best built into Cousteau and then just used/wrapped in Magellan, but I'd also (unsurprisingly) suggest more human-friendly names :-)

```python
from ripe.atlas.cousteau.keys import Key

create_key = Key.get(keys.CREATE)
results_key = Key.get(keys.RESULTS)
```

In this logic though, there's no means of preference between more than one existing key, so maybe an optional partial fingerprint might be handy?

```python
from ripe.atlas.cousteau.keys import Key

create_key = Key.get(keys.CREATE, fingerprint="10dead-beef")
results_key = Key.get(keys.RESULTS, fingerprint="123456-7890")
```

**Comment by danielquinn** [comment]
To clarify ('cause I didn't understand at first) this is about locally defining a central place for key storage so that Cousteau and Magellan can both access this data.  Presently, the best suggestion is `${HOME}/.config/ripe-atlas` which sounds fine by me, but I would extend that:

    .config/ripe-atlas/
        /config.yaml
    .config/ripe-atlas/tools/
        /config.yaml
        /cache-2.7.10.db
    .config/ripe-atlas/cousteau/
        /config.yaml

@phicoh has also suggested that we use the package version in the config files, so that we can gracefully migrate configs without losing old versions should the user wish to roll back:

    .config/ripe-atlas/
        /config.yaml
    .config/ripe-atlas/tools/
        /config-1.1.yaml
        /config-1.2.yaml
        /cache-2.7.10.db
    .config/ripe-atlas/cousteau/
        /config-1.0.yaml

**Comment by chrisamin** [comment]
The measurement aliases seems to suit this purpose for now.
